version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - api
      - redis
    command: celery -A celery_worker.celery_app worker --loglevel=info

  scheduler:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - api
      - db
    command: python scheduler.py

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nasajon_integration
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:

